# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'xbNavBarViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xbNavBarViewDemo

  #自动布局
  pod 'SnapKit'
  
end
